Codo/urls.py

from django.contrib import admin 
from django.urls import path , include


from .views import IndexPage
from .views import Funcion
from .views import Comentarios
from .views import Login
from .views import Dejar_comentario
from .views import Editar
from .views import Crear

from .views import logout_view


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", IndexPage.as_view(), name="index"),
    path("comentarios", Comentarios.as_view(), name="comentarios"),
    path("login", Login.as_view(), name="login"),
    path("dejar_comentario", Dejar_comentario.as_view(), name="dejar_comentario"),
    path("edit", Editar.as_view(), name="edit"),
    path("crear", Crear.as_view(), name="crear"),
    path("store/", include("store_app.urls")),
    path('logout/', logout_view, name='logout'),

]


store_app/urls.py
from django.contrib import admin
from django.urls import path 

from .views import (
    StoreListView,
    StoreCreateView,
    StoreUpdateView, 
    StoreDeleteView,

)

app_name = "store"

urlpatterns = [
    path("", StoreListView.as_view(), name="all"),
    path("create/", StoreCreateView.as_view(), name="create"),
    path("<int:pk>/delete/", StoreDeleteView.as_view(), name="delete"),
    path("<int:pk>/update/", StoreUpdateView.as_view(), name="update")
]

store_app/models.py
from django.db import models
from django.db import models
from django.db.models import Model


class Store(Model):
    """
    Atributos de clase que son usadas por herencia de la clase Model

    """
    id = models.FloatField(primary_key=True,blank=False, default=1)
    nombre  =  models.CharField(max_length=200, default="...")
    link  = models.CharField(max_length=800, default="...")
    imagen =  models.CharField(max_length=200, default="...")

    # podemos crear la tabla con un nombre especifico pero se lo tenemos
    # que indicar directamente en la metaclase

    class Meta: 
        db_table = "ias" # Definimos el nombre de la tabla

    def __str__(self):
        return f"La IA: {self.nombre}, su link es: {self.link}"

    def get_fields(self): # Aca se traen todos los atributos excepto el nombre
        """
        Obtiene los campos y sus valores asociados de un objeto.

        Retorna una lista de tuplas donde cada tupla contiene el nombre legible
        del campo y el valor correspondiente del objeto actual.

        Nota:
        - La función utiliza los metadatos del modelo (self.__class__._meta.fields)
        para obtener la lista de campos, excluyendo el primer campo que generalmente
        es la clave primaria.
        - La tupla resultante tiene el formato (nombre_legible_del_campo, valor_del_campo).

        Ejemplo:
        Si tienes un modelo `MiModelo` con campos 'nombre' y 'edad', y un objeto `obj`
        de ese modelo con nombre='Juan' y edad=25, llamar a `obj.get_fields()` podría
        retornar [('nombre', 'Juan'), ('edad', 25)].

        Returns:
        List[tuple]: Lista de tuplas donde cada tupla contiene el nombre del campo
                    y el valor asociado del objeto actual.
        """
        return [
            (field.verbose_name, field.value_from_object(self))
            for field in self.__class__._meta.fields[1:]
        ]


store_app/forms.py
from django import forms
from .models import Store

class StoreForm(forms.ModelForm):
    class Meta:
        model = Store
        fields = '__all__'  # Esto incluirá todos los campos de tu modelo Store en el formulario

Codo/views.py
from django.views.generic import TemplateView
from django.shortcuts import render
from django.contrib.auth import logout
from django.shortcuts import redirect


class IndexPage(TemplateView):
    template_name = "index.html"

class Funcion(TemplateView):
    template_name = "byFunction.html"

class Comentarios(TemplateView):
    template_name = "comments.html"

class Login(TemplateView):
    template_name = "fLogin.html"

class Dejar_comentario(TemplateView):
    template_name = "fComments.html"

class Editar(TemplateView):
    template_name = "edit.html"

class Crear(TemplateView):
    template_name = "fNewIA.html"

def logout_view(request):
    logout(request)
    return redirect('index')


store_app/views.py

from django.urls import reverse_lazy
from django.views import View

from django.views.generic.list import ListView # Me permite ver todos los items
from django.views.generic.edit import DeleteView, UpdateView, CreateView
from django.views.generic.detail import DetailView # Me permite ver un elemento individual

from .models import Store
from django.shortcuts import redirect, render
from django.contrib.auth import logout


def logout_view(request):
    logout(request)
    return redirect('index')


class StoreBaseView(View):
    template_name = 'store.html'
    model = Store
    fields = '__all__'
    success_url = reverse_lazy('store:all')


class StoreListView(StoreBaseView,ListView):
    """
    ESTO ME PERMITE CREAR UNA VISTA CON LOS StoreS
    """

class StoreDetailView(StoreBaseView,DetailView):
    template_name = "store_detail.html"


class StoreCreateView(StoreBaseView,CreateView):
    template_name = "store_create.html"
    extra_context = {"tipo": "Crear Store"}

class StoreUpdateView(StoreBaseView,UpdateView):
    template_name = "store_create.html"
    extra_context = {"tipo": "Actualizar Store"}

class StoreDeleteView(StoreBaseView,DeleteView):
    template_name = "store_delete.html"
    extra_context = {"tipo": "Borrar Store"}










store_app/templates/store.html
{% load static %}
<!DOCTYPE html>
<html lang="es-AR">

<head>
  <meta charset="UTF-8">
  <title>Inteligencias por función</title>
  <link rel="icon" type="image/x-icon" href="{% static './media/icons/logo_g19.png' %}">
  <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1">
  <meta name="keywords" content="">
  <meta name="description" content="Front-End del trabajo práctico del curso Full-Stack Python 2023 2C - Codo a Codo">
  <meta name="author" content="Valentín, Matías, Julián, Mario">

  <link rel="stylesheet" href="{% static './css/styles.css' %}" />
  <link rel="stylesheet" href="{% static './css/main.css' %}" />
</head>

<body>
  <header id="headerPri">

    <div>
      <img src="{% static './media/icons/logo_g19.png' %}" width="55" height="55" alt="Logo del Portfolio - Grupo-19"
        title="Grupo-19" />
    </div>
    <h1>IAs list</h1>

    <div class="oculto">
      {% if user.is_authenticated %}
      <a href="{% url 'store:create' %}" class="btnNew" type="button" title="Agregar Inteligencia Artificial">
          <b>+</b> Agregar IA
      </a>
      {% else %}
      {% endif %}
    </div>

    <nav id="menuPri">
      <ul>
        <li><a href="/">Inicio</a></li>
        <li><a href="{% url 'store:all' %}">IAs</a></li>
        <li><a href="{% url 'comentarios' %}">Comentarios</a></li>
        {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}"><i class="bi bi-x-square"></i></a></li>
        {% else %}
            <li><a href="{% url 'login' %}"><i class="bi bi-person-circle"></i></a></li>
        {% endif %}
      </ul>
    </nav>
    <button id="btnMenuPri" type="button"></button>

  </header>

  <main>
    <section id="iaByFunctionList">

    <div id="iaList">
      {% for store in store_list %}
      <ul>
        <li>
          {% if user.is_authenticated %}
          <div>
            <a href="{% url 'store:delete' store.id %}">❌</a>
            <a href="{% url 'store:update' store.id %}">🖋️</a>
          </div>
          {% endif %}
          <a href="{{store.link}}" target="_blank">
          <img src="{{store.imagen}}" title= "{{store.nombre}}" alt="{{store.nombre}}">
        </li>
      </ul>
      {% endfor %}
    </div>

    </section>

    <section id="comments">
      <a href="{% url 'dejar_comentario' %}" class="bi bi-chat-right-text"> dejanos tu comentario!</a>
    </section> 
  </main>

  <footer>
    <section>
      <p>CaC FS PYTHON 2023</p>
      <p><strong>Comisión 23507</strong></p>
      <p><i>Grupo 19</i></p>
    </section>

    <section>
      <article>
        <span>Matías Andrés Sustersic</span>
        <a class="bi bi-envelope" href="mailto:msuster93@gmail.com?$subject=Contacto%20desde%20IAs list"
          title="Email de Matías Andrés Sustersic"></a>
        <a class="bi bi-whatsapp" href="https://api.whatsapp.com/send?phone=5491123917168" target="_blank"
          title="Whatsapp de Matías Andrés Sustersic"></a>
        <a class="bi bi-github iconRed iconRedG icon tresSeg" href="https://github.com/Msustersic" target="_blank"
          title="GitHub"></a>
      </article>
      <article>
        <span>Mario Rubén Lerman</span>
        <a class="bi bi-envelope" href="mailto:mariolerman@gmail.com?$subject=Contacto%20desde%20IAs list"
          title="Email de Mario Rubén Lerman"></a>
        <a class="bi bi-whatsapp"
          href="https://api.whatsapp.com/send?phone=5491145777353&text=Contacto%20desde%20IAs list" target="_blank"
          title="Whatsapp de Mario Lerman"></a>
        <a class="bi bi-github iconRed iconRedG icon tresSeg" href="https://github.com/Marior70" target="_blank"
          title="GitHub"></a>
      </article>
      <article>
        <span>Alejo Podbielski</span>
        <a class="bi bi-envelope" href="mailto:valentinpodbielski71@gmail.com?$subject=Contacto%20desde%20IAs list"
          title="Email de Alejo Podbielski"></a>
        <a class="bi bi-whatsapp" href="https://api.whatsapp.com/send?phone=5491162037019" target="_blank"
          title="Whatsapp de Alejo Podbielski"></a>
        <a class="bi bi-github iconRed iconRedG icon tresSeg" href="https://github.com/Valentinpodbielski"
          target="_blank" title="GitHub"></a>
      </article>
      <article>
        <span>Julián Albornoz</span>
        <a class="bi bi-envelope" href="mailto:julian.alborno05@gmail.com?$subject=Contacto%20desde%20IAs list"
          title="Email de Julián Albornoz"></a>
        <a class="bi bi-whatsapp" href="https://api.whatsapp.com/send?phone=5491150051266" target="_blank"
          title="Whatsapp de Julián Albornoz"></a>
        <a class="bi bi-github iconRed iconRedG icon tresSeg" href="https://github.com/julianliyo" target="_blank"
          title="GitHub"></a>
      </article>
    </section>
    <img src="{% static './media/icons/logo_tecno.png' %}" alt="Logo de CSS-3" style="width: 50px;height: 33.5px;">
  </footer>

</body>

</html>

store_app/templates/store_create.html
{% load static %}
<!DOCTYPE html>
<html lang="es-AR">

<head>
  <meta charset="UTF-8">
  <title>Crear IA</title>
  <link rel="icon" type="image/x-icon" href="{% static './media/icons/logo_g19.png' %}" />
  <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1" />
  <meta name="keywords" content="" />
  <meta name="description" content="Front-End del trabajo práctico del curso Full-Stack Python 2023 2C - Codo a Codo" />
  <meta name="author" content="Valentín, Matías, Julián, Mario" />

  <link rel="stylesheet" href="{% static './css/styles.css' %}" />
</head>

<body>
  <header id="headerPri">

    <div>
      <img src="{% static './media/icons/logo_g19.png' %}" width="55" height="55" alt="Logo del Portfolio - Grupo-19"
        title="Grupo-19" />
    </div>
    <h1>IAs list</h1>
    <nav id="menuPri">
      <ul>
        <li><a href="/">Inicio</a></li>
        <li><a href="{% url 'store:all' %}">Funciones</a></li>
        <li><a href="{% url 'comentarios' %}">Comentarios</a></li>
        <li><a href="{% url 'login' %}"><i class="bi bi-person-circle"></i></a></li>
      </ul>
    </nav>

    <button id="btnMenuPri" type="button"></button>

  </header>

  <main>
    <form id="fNewIa" method="post">
        {% csrf_token %}
        <div>{{ form.as_p }}</div>
        <input id="bb" type="submit" value="{{ tipo }}" style="height: 50%"/>
    </form>
</main>
  

  <footer>
    <section>
      <p>CaC FS PYTHON 2023</p>
      <p><strong>Comisión 23507</strong></p>
      <p><i>Grupo 19</i></p>
    </section>

    <section>
      <article>
        <span>Matías Andrés Sustersic</span>
        <a class="bi bi-envelope" href="mailto:msuster93@gmail.com?$subject=Contacto%20desde%20IAs list"
          title="Email de Matías Andrés Sustersic"></a>
        <a class="bi bi-whatsapp" href="https://api.whatsapp.com/send?phone=5491123917168" target="_blank"
          title="Whatsapp de Matías Andrés Sustersic"></a>
        <a class="bi bi-github iconRed iconRedG icon tresSeg" href="https://github.com/Msustersic" target="_blank"
          title="GitHub"></a>
      </article>
      <article>
        <span>Mario Rubén Lerman</span>
        <a class="bi bi-envelope" href="mailto:mariolerman@gmail.com?$subject=Contacto%20desde%20IAs list"
          title="Email de Mario Rubén Lerman"></a>
        <a class="bi bi-whatsapp"
          href="https://api.whatsapp.com/send?phone=5491145777353&text=Contacto%20desde%20IAs list" target="_blank"
          title="Whatsapp de Mario Lerman"></a>
        <a class="bi bi-github iconRed iconRedG icon tresSeg" href="https://github.com/Marior70" target="_blank"
          title="GitHub"></a>
      </article>
      <article>
        <span>Alejo Podbielski</span>
        <a class="bi bi-envelope" href="mailto:valentinpodbielski71@gmail.com?$subject=Contacto%20desde%20IAs list"
          title="Email de Alejo Podbielski"></a>
        <a class="bi bi-whatsapp" href="https://api.whatsapp.com/send?phone=5491162037019" target="_blank"
          title="Whatsapp de Alejo Podbielski"></a>
        <a class="bi bi-github iconRed iconRedG icon tresSeg" href="https://github.com/Valentinpodbielski"
          target="_blank" title="GitHub"></a>
      </article>
      <article>
        <span>Julián Albornoz</span>
        <a class="bi bi-envelope" href="mailto:julian.alborno05@gmail.com?$subject=Contacto%20desde%20IAs list"
          title="Email de Julián Albornoz"></a>
        <a class="bi bi-whatsapp" href="https://api.whatsapp.com/send?phone=5491150051266" target="_blank"
          title="Whatsapp de Julián Albornoz"></a>
        <a class="bi bi-github iconRed iconRedG icon tresSeg" href="https://github.com/julianliyo" target="_blank"
          title="GitHub"></a>
      </article>
    </section>
    <img src="../../assets/media/icons/logo_tecno.png" alt="Logo de CSS-3" style="width: 50px;height: 33.5px;">
  </footer>

  <script src="{% static './js/comments/idxFComment.js' %}" type="module"></script>
  <script src="{% static './js/index.js' %}"></script>
</body>

</html>

store_app/templates/store_delete.html
{% load static %}
<!DOCTYPE html>
<html lang="es-AR">

<head>
  <meta charset="UTF-8">
  <title>Crear IA</title>
  <link rel="icon" type="image/x-icon" href="{% static './media/icons/logo_g19.png' %}" />
  <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1" />
  <meta name="keywords" content="" />
  <meta name="description" content="Front-End del trabajo práctico del curso Full-Stack Python 2023 2C - Codo a Codo" />
  <meta name="author" content="Valentín, Matías, Julián, Mario" />

  <link rel="stylesheet" href="{% static './css/styles.css' %}" />
</head>

<body>
  <header id="headerPri">

    <div>
      <img src="{% static './media/icons/logo_g19.png' %}" width="55" height="55" alt="Logo del Portfolio - Grupo-19"
        title="Grupo-19" />
    </div>
    <h1>IAs list</h1>
    <nav id="menuPri">
      <ul>
        <li><a href="/">Inicio</a></li>
        <li><a href="{% url 'store:all' %}">Funciones</a></li>
        <li><a href="{% url 'comentarios' %}">Comentarios</a></li>
        <li><a href="{% url 'login' %}"><i class="bi bi-person-circle"></i></a></li>
      </ul>
    </nav>

    <button id="btnMenuPri" type="button"></button>

  </header>

  <main>
    <h2>Estas seguro de borrar la IA?</h2>
    <h2>{{store.nombre}}</h2>
    <form id="fNewIa" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="{{ tipo }}" style="height: 50%"/>
    </form>
  </main>


  <footer>
    <section>
      <p>CaC FS PYTHON 2023</p>
      <p><strong>Comisión 23507</strong></p>
      <p><i>Grupo 19</i></p>
    </section>

    <section>
      <article>
        <span>Matías Andrés Sustersic</span>
        <a class="bi bi-envelope" href="mailto:msuster93@gmail.com?$subject=Contacto%20desde%20IAs list"
          title="Email de Matías Andrés Sustersic"></a>
        <a class="bi bi-whatsapp" href="https://api.whatsapp.com/send?phone=5491123917168" target="_blank"
          title="Whatsapp de Matías Andrés Sustersic"></a>
        <a class="bi bi-github iconRed iconRedG icon tresSeg" href="https://github.com/Msustersic" target="_blank"
          title="GitHub"></a>
      </article>
      <article>
        <span>Mario Rubén Lerman</span>
        <a class="bi bi-envelope" href="mailto:mariolerman@gmail.com?$subject=Contacto%20desde%20IAs list"
          title="Email de Mario Rubén Lerman"></a>
        <a class="bi bi-whatsapp"
          href="https://api.whatsapp.com/send?phone=5491145777353&text=Contacto%20desde%20IAs list" target="_blank"
          title="Whatsapp de Mario Lerman"></a>
        <a class="bi bi-github iconRed iconRedG icon tresSeg" href="https://github.com/Marior70" target="_blank"
          title="GitHub"></a>
      </article>
      <article>
        <span>Alejo Podbielski</span>
        <a class="bi bi-envelope" href="mailto:valentinpodbielski71@gmail.com?$subject=Contacto%20desde%20IAs list"
          title="Email de Alejo Podbielski"></a>
        <a class="bi bi-whatsapp" href="https://api.whatsapp.com/send?phone=5491162037019" target="_blank"
          title="Whatsapp de Alejo Podbielski"></a>
        <a class="bi bi-github iconRed iconRedG icon tresSeg" href="https://github.com/Valentinpodbielski"
          target="_blank" title="GitHub"></a>
      </article>
      <article>
        <span>Julián Albornoz</span>
        <a class="bi bi-envelope" href="mailto:julian.alborno05@gmail.com?$subject=Contacto%20desde%20IAs list"
          title="Email de Julián Albornoz"></a>
        <a class="bi bi-whatsapp" href="https://api.whatsapp.com/send?phone=5491150051266" target="_blank"
          title="Whatsapp de Julián Albornoz"></a>
        <a class="bi bi-github iconRed iconRedG icon tresSeg" href="https://github.com/julianliyo" target="_blank"
          title="GitHub"></a>
      </article>
    </section>
    <img src="../../assets/media/icons/logo_tecno.png" alt="Logo de CSS-3" style="width: 50px;height: 33.5px;">
  </footer>

  <script src="{% static './js/comments/idxFComment.js' %}" type="module"></script>
  <script src="{% static './js/index.js' %}"></script>
</body>

</html>

templates/comments.html
{% load static %}
<!DOCTYPE html>
<html lang="es-AR">

<head>
  <meta charset="UTF-8">
  <title>IAs - comments received</title>
  <link rel="icon" type="image/x-icon" href="{% static './media/icons/logo_g19.png' %}">
  <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1">
  <meta name="keywords" content="">
  <meta name="description" content="Front-End del trabajo práctico del curso Full-Stack Python 2023 2C - Codo a Codo">
  <meta name="author" content="Valentín, Matías, Julián, Mario">

  <link rel="stylesheet" href="{% static './css/styles.css' %}" />
</head>

<body>
  <header id="headerPri">

    <a id="logoSitio" href="https://net-m.myddns.me">
      <img src="{% static './media/icons/logo_g19.png' %}" width="55" height="55" alt="Logo del Portfolio - Grupo-19"
        title="Grupo-19" />
    </a>
    <h1>IAs list</h1>
    <nav id="menuPri">
      <ul>
        <li><a href="/">Inicio</a></li>
        <li><a href="{% url 'store:all' %}">IAs</a></li>
        <li><a href="{% url 'comentarios' %}">Comentarios</a></li>
        {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}"><i class="bi bi-x-square"></i></a></li>
        {% else %}
            <li><a href="{% url 'login' %}"><i class="bi bi-person-circle"></i></a></li>
        {% endif %}
      </ul>
    </nav>

    <button id="btnMenuPri" type="button"></button>

  </header>

  <main>
    <h2 id="commentsID">Comentarios recibidos</h2>
    <section id="commentsList">
      <ul id="dataList">
        
      </ul>
    </section>
    <section id="comments">
      <a href="../pages/forms/fComments.html" class="bi bi-chat-right-text"> dejanos tu comentario!</a>
    </section>
  </main>

  <footer>
    <section>
      <p>CaC FS PYTHON 2023</p>
      <p><strong>Comisión 23507</strong></p>
      <p><i>Grupo 19</i></p>
    </section>

    <section>
      <article>
        <span>Matías Andrés Sustersic</span>
        <a class="bi bi-envelope" href="mailto:msuster93@gmail.com?$subject=Contacto%20desde%20IAs list"
          title="Email de Matías Andrés Sustersic"></a>
        <a class="bi bi-whatsapp" href="https://api.whatsapp.com/send?phone=5491123917168" target="_blank"
          title="Whatsapp de Matías Andrés Sustersic"></a>
        <a class="bi bi-github iconRed iconRedG icon tresSeg" href="https://github.com/Msustersic" target="_blank"
          title="GitHub"></a>
      </article>
      <article>
        <span>Mario Rubén Lerman</span>
        <a class="bi bi-envelope" href="mailto:mariolerman@gmail.com?$subject=Contacto%20desde%20IAs list"
          title="Email de Mario Rubén Lerman"></a>
        <a class="bi bi-whatsapp"
          href="https://api.whatsapp.com/send?phone=5491145777353&text=Contacto%20desde%20IAs list" target="_blank"
          title="Whatsapp de Mario Lerman"></a>
        <a class="bi bi-github iconRed iconRedG icon tresSeg" href="https://github.com/Marior70" target="_blank"
          title="GitHub"></a>
      </article>      
      <article>
        <span>Alejo Podbielski</span>
        <a class="bi bi-envelope" href="mailto:valentinpodbielski71@gmail.com?$subject=Contacto%20desde%20IAs list"
          title="Email de Alejo Podbielski"></a>
        <a class="bi bi-whatsapp" href="https://api.whatsapp.com/send?phone=5491162037019" target="_blank"
          title="Whatsapp de Alejo Podbielski"></a>
        <a class="bi bi-github iconRed iconRedG icon tresSeg" href="https://github.com/Valentinpodbielski" target="_blank"
          title="GitHub"></a>
      </article>
      <article>
        <span>Julián Albornoz</span>
        <a class="bi bi-envelope" href="mailto:julian.alborno05@gmail.com?$subject=Contacto%20desde%20IAs list"
          title="Email de Julián Albornoz"></a>
        <a class="bi bi-whatsapp" href="https://api.whatsapp.com/send?phone=5491150051266" target="_blank"
          title="Whatsapp de Julián Albornoz"></a>
        <a class="bi bi-github iconRed iconRedG icon tresSeg" href="https://github.com/julianliyo" target="_blank"
          title="GitHub"></a>
      </article>
    </section>
    <img src="{% static './media/images/logo_tecno.png' %}" alt="Logo de CSS-3" style="width: 50px;height: 33.5px;">
  </footer>

  <script src="static\js\index.js"></script>
  <script src="static\js\comments\idxComments.js" type="module"></script>
</body>



</html>